name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: First run - Download Android SDK
        run: |
          buildozer android debug || true
          echo "===== Cek lokasi SDK ====="
          find /github/home /home -type d -name "android-sdk" 2>/dev/null || true

      - name: Setup Android SDK & licenses
        run: |
          SDKMANAGER=$(find $HOME -name sdkmanager 2>/dev/null | head -n 1)
          
          if [ -z "$SDKMANAGER" ]; then
            echo "sdkmanager tidak ketemu, coba path default"
            SDKMANAGER="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
          fi
          
          echo "Menggunakan sdkmanager: $SDKMANAGER"
          
          yes | $SDKMANAGER --licenses > /dev/null || true
          yes | $SDKMANAGER "build-tools;34.0.0" "platforms;android-34" "platform-tools" || true
          
          echo "=== Cek build-tools ==="
          find $HOME -path "*/build-tools/*/aidl" 2>/dev/null || echo "aidl belum ketemu"

      - name: Clean & Build final
        run: |
          buildozer android clean || true
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
          if-no-files-found: error
